version: '3.2'

services:
    postgis:
      image: bde2020/pilot-sc4-postgis:v0.10.0
      build:
        context: ./postgis
      hostname: postgis       
      container_name: postgis
      restart: unless-stopped
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=password
      networks:
        - pilot-sc4-net
        
    rserve:
     build:
       context: ./rserve    
     image: bde2020/pilot-sc4-rserve:v0.10.0
     hostname: rserve
     container_name: rserve
     restart: unless-stopped
     ports:
       - "6311:6311"
     environment:
       - SERVICE_PRECONDITION=postgis:5432
       - POSTGRES_PASSWORD=password
     depends_on:
       - postgis
     networks:
       - pilot-sc4-net
    
networks:
    pilot-sc4-net:
        external: true
